### ISSUE TITLE
`よくわかるcontextの使い方` へのコメント

### ISSUE THREAD

**Issue by syumai** [saki-engineering/ZennDoc#3]
* [よくわかるcontextの使い方](https://zenn.dev/hsaki/books/golang-context) へのコメントです
  - 非常に便利な記事をありがとうございます！
* 軽微な修正と、内容に対しての提案を含んでいます
  - 提案の方は `こうであってもよいのでは` と言う内容ですので、もし良さそうであれば検討いただけると幸いです 🙏 

#### context導入前 - doneチャネルを用いる場合のキャンセル処理

* generator関数内
  - コメントアウトしたくない箇所もしちゃってそうでした

```diff
- // case out <- num: これが時間がかかっているという想定
+ case out <- num: // これが時間がかかっているという想定
```

#### 自動タイムアウト機能の追加 - WithTimeout関数

* 例の内容を見た感じ、2秒後ではなく1秒後のようでした

```diff
- 例えば、以下の2つはどちらも「2秒後にタイムアウトさせるcontext」を生成します。
+ 例えば、以下の2つはどちらも「1秒後にタイムアウトさせるcontext」を生成します。
```

#### contextを使用した値の伝達

typo

```diff
- 上の処理は、contextを力を最大限使えば、以下のように書き直すことができます。
+ 上の処理は、contextの力を最大限使えば、以下のように書き直すことができます。
```

#### ゴールーチンセーフではない値

typo

```diff
- 繰り返しますが、contextにゴールーチンセーフな値を渡すべきではありません。
+ 繰り返しますが、contextにゴールーチンセーフでない値を渡すべきではありません。
```

### 09 - contextの具体的な使用例

typo

```diff
- handlersパッケージ内では、ハンドラを表す独自型としてMyHandlerFuncというものを定義しました。
- この型を満たす変数の一つとして、ハンドラMyHandleFuncを定義しました。
+ handlersパッケージ内では、ハンドラを表す独自型としてMyHandleFuncというものを定義しました。
+ この型を満たす変数の一つとして、ハンドラGetGreetingを定義しました。
```

#### context導入前 - doneチャネルを用いる場合のキャンセル処理

main関数内の処理ですが、for loopの中で毎回time.Afterを呼んでいるので、ループの度にdeadlineが初期化されているように見えました。
contextを使った実装と同一の内容にするなら、for loop外で事前にdeadline用のchannelを用意しておいても良さそうです。

```go
func main() {
	// doneチャネルがcloseされたらキャンセル
	done := make(chan struct{})
	gen := generator(done, 1)
	deadlineCh := time.After(time.Second) // タイムアウト用のチャネルを用意する

	wg.Add(1)

LOOP:
	for i := 0; i < 5; i++ {
		select {
		case result := <-gen: // genから値を受信できた場合
			fmt.Println(result)
		case <-deadlineCh: // 1秒間受信できなかったらタイムアウト
    	...
```

### 08 - Valueメソッドを有効に使うtips

空の構造体型に対してkeyの型を定義するパターンも一般的なので、こちらを紹介していてもいいかも知れません。

- 例) `type ctxKey struct{}`

こちらも、型をprivateに定義しておけば、package外から利用することが出来ないので安全に作れますし、空の構造体なので[メモリのアロケーションが発生しない](https://dave.cheney.net/2014/03/25/the-empty-struct)利点もあります。
golang/go配下のソースコードに検索をかけたところ、test以外のコードの多くでこちらのパターンが採用されているようでした (業務で見かけたコードもほとんどこちらのパターンでした)
- https://github.com/search?q=context.WithValue%28+repo%3Agolang%2Fgo+language%3AGo&type=Code&ref=advsearch&l=Go&l=

**Comment by saki-engineering** [comment]
コメントありがとうございます！typoがあまりに多すぎて自分でも引いてます←

以下リプです

## 軽微な修正
### 05 - Deadlineメソッドとタイムアウト
#### context導入前 - doneチャネルを用いる場合のキャンセル処理
```go
 case out <- num: // これが時間がかかっているという想定
```
本番のコードだと「`case out <- num`部分はコメントアウトしてないのに、時間がかかる」という状態になると思うので、ここはコメントアウトすべきではない場所では？というこのご指摘はある意味正しいといえば正しいんです。

ただ実際に記事に載せているコードだと、`out <- num`は外との通信がなくていつでも実行できてしまう部分なので、ここをコメントアウトさせておくことで「擬似的なタイムアウト」をさせてる、という感じです。
```go
 // case out <- num: これが時間がかかっているという想定
 case out <- num: // これが時間がかかっているという想定
```

## 提案
### 05 - Deadlineメソッドとタイムアウト
言われれみればおっしゃる通りです、普通にミスでした！

### 08 - Valueメソッドを有効に使うtips
空構造体を使う方、いいですね！
「業務ではこちらの方が多い」という経験談ベースの情報、ありがたいです。（独学だと何が普通で何が普通でないかの感覚が薄い）
ちょっと書き足します！

**Comment by syumai** [comment]
> ただ実際に記事に載せているコードだと、out <- numは外との通信がなくていつでも実行できてしまう部分なので、ここをコメントアウトさせておくことで「擬似的なタイムアウト」をさせてる、という感じです。

なるほど！説明のためにDoneチャネルがcloseされるまで意図的にblockさせていたと言うことですね、理解しました 👍 

提案の方も対応ありがとうございます！

フィードバックは以上なので、こちらのIssueはよしななタイミングでCloseしちゃってください 🙏

**Comment by syumai** [comment]
対応いただいたようなのでCloseします。ありがとうございました！
